course/urls.py
from django import urls
from django.urls import path
from .import views

app_name = 'course'

urlpatterns = [
    path('<int:course_id>/',views.Deatail_Course,name='detailcourse'),  
    path('<int:course_id>/<int:lesson_id>/game/1/<int:num_scores>/<int:is_doing>/<int:is_get>/',views.get_post_data_game_word_card,name='lesson_game_card'),
    path('<int:course_id>/<int:lesson_id>/game/2/<int:num_scores>/<int:is_doing>/<int:is_get>/',views.get_post_data_game_golden_fish,name='lesson_game_golden_fish'),
    path('<int:course_id>/<int:lesson_id>/',views.View_Detail_Lesson,name='detaillesson'),
    path('<int:course_id>/violympic-end-course/<int:vio_one_id>/',views.Violympic_End_Course,name='violympic_end_course'),
    path('<int:course_id>/<int:lesson_id>/exercise/3/<int:num_scores>/<int:is_doing>/<int:is_get>/',views.get_post_data_exercise_arrange,name='lesson_arrange'),
    path('<int:course_id>/<int:lesson_id>/exercise/2/<int:num_scores>/<int:is_doing>/<int:is_get>/',views.get_post_data_exercise_missing,name='lesson_missing'),
    path('<int:course_id>/<int:lesson_id>/exercise/1/<int:num_scores>/<int:is_doing>/<int:is_get>/',views.get_post_data_exercise_choice,name='lesson_choice'),  
]

home/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import LogoutView

app_name = 'home'

urlpatterns = [
    path('',views.index,name='index'),
    path('about/',views.About,name='about'),
    path('contact/',views.Contact,name='contact'),
    
    path('search/',views.search_text,name='search-text'),
    path('login/',views.loginUser.as_view(),name='loginUser'),
    path('register/',views.registerUser.as_view(),name='registerUser'),
    path('register-teacher/',views.registerTeacher.as_view(),name='registerTeacher'),
    path('logout/',LogoutView.as_view(),name='logoutUser'),
]

learnEnglish/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
#

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('home.urls')),
    path('course/',include('course.urls')),
    path('order/',include('order.urls')),
    path('payment/',include('payment.urls')),
    path('dashboard/',include('usermember.urls')),
    path('competition/',include('competition.urls')),
   
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

order/urls.py
from django.urls import path
from .import views
app_name = 'order'

urlpatterns = [
    path('add-to-cart/<int:course_id>/<int:id_vip>/',views.add_to_cart,name='add-to-cart'),
    path('remove-item-from-cart/<int:course_id>/',views.remove_item_from_cart,name='remove-item-from-cart'),
    path('cart-view/',views.cart_view,name='cart'),
    path('register-course/<int:course_id>/',views.register_course,name='register_course'),
    
]

course/models.py
from django.db import models
from django.core.validators import  MaxValueValidator, MinValueValidator 
from django.urls import reverse
import xlrd
from django.conf import settings
# Create your models here.

class Course(models.Model):
    title = models.CharField(max_length=45)
    course_img = models.ImageField()
    course_banner = models.ImageField()
    description = models.TextField(default='')
    excerpt = models.TextField(default='',max_length=300)
    price_month = models.DecimalField(default=0,max_digits=8, decimal_places=0)
    price_quarter = models.DecimalField(default=0,max_digits=8, decimal_places=0)
    price_year = models.DecimalField(default=0,max_digits=8, decimal_places=0)
    price_lifetime = models.DecimalField(default=0,max_digits=8, decimal_places=0)
    discounted_price = models.IntegerField(default=0)
    status = models.BooleanField(default=True)

    def __str__(self):
        return self.title
    def get_add_to_cart_url(self):
        return reverse("course:add-to-cart", kwargs = {
            'course_id':self.id
        })



class Chapter(models.Model):
    course = models.ForeignKey(Course,on_delete=models.CASCADE)
    title = models.CharField(default='',max_length=45)
    title_vi = models.CharField(default='',max_length=45)

    def __str__(self):
        return '%s ,--- %s' % (self.course.title,self.title)
class Lesson(models.Model):
    titlesub_choice = ((0,""),(1,"Letters & Phonics"), (2,"Numbers"),(3,"Words"),(4,"Sentences"),(5,"Games"),(6,"Phonics"))
    titlesub_vi_choice = ((0,""),(1,"Chữ cái và âm"), (2,"Chữ số"),(3,"Từ vựng"),(4,"Mẫu câu"),(5,"Trò chơi"),(6,"Âm"))
    icon_choice = ((0,""),(1,"letter_phonic.png"), (2,"inumber.png"),(3,"iword.png"),(4,"isentence.png"),(5,"igames.png"),(6,"iphonics.png"))
    
    chapter = models.ForeignKey(Chapter,on_delete=models.CASCADE,null=True)
    titlesub = models.IntegerField(choices=titlesub_choice,default=0)
    titlesub_vi = models.IntegerField(choices=titlesub_vi_choice,default=0)
    icon = models.IntegerField(choices=icon_choice,default=0)
    description = models.CharField(default='',max_length=45)
    description_vi = models.CharField(default='',max_length=45)
    video = models.CharField(default='',max_length=150)
    def __str__(self):
        return '%s ,--- %s ,---%s,' % (self.chapter.course.title,self.chapter.title,self.get_titlesub_display())


class TypeGame(models.Model):
    title = models.CharField(default='',max_length=50)

    def __str__(self):
        return self.title


class ImageOfGame(models.Model):
    img = models.ImageField(upload_to='game/memory_word_card/')

    def __str__(self):
        return self.img.url

class GameWordMemoryCards(models.Model):
    lesson = models.ForeignKey(Lesson,on_delete=models.CASCADE)
    type = models.ForeignKey(TypeGame,on_delete=models.CASCADE)
    imgs = models.ManyToManyField(ImageOfGame)
    def __str__(self):
        return f"Game card of {self.lesson}"

class GameGoldenFish(models.Model):
    lesson = models.ForeignKey(Lesson,on_delete=models.CASCADE)
    type = models.ForeignKey(TypeGame,on_delete=models.CASCADE)
    file_excel =  models.FileField(upload_to='game/golden_fish/', max_length=100)
    num_rows = models.PositiveSmallIntegerField(default=0)

    def __str__(self):
        return f"Game golden fish of {self.lesson}"

    # overise save
    def save(self, *args, **kwargs):
        super(GameGoldenFish, self).save(*args, **kwargs) 
        data= xlrd.open_workbook(settings.BASE_DIR + self.file_excel.url) #open a file
        table = data.sheet_by_index(0) #Get a worksheet
        nrows = table.nrows #Rows
        ncols = table.ncols 
        self.num_rows = nrows - 1
        super().save(*args, **kwargs)  
  
class TypeExercise(models.Model):
    title = models.CharField(default='',max_length=50)
    

    def __str__(self):
        return self.title


class ExerciseChoiceAnswer(models.Model):
    lesson = models.ForeignKey(Lesson,on_delete=models.CASCADE)
    type = models.ForeignKey(TypeExercise,on_delete=models.CASCADE)
    file_excel =  models.FileField(upload_to='exercise/choice_answer/', max_length=100,null=True)
    num_rows = models.PositiveSmallIntegerField(default=0)
       
    def __str__(self):
        return '%s ,--- %s ,---%s : %s' % (self.lesson.chapter.course.title,self.lesson.chapter.title,self.lesson.get_titlesub_display(),self.type.title)
    
    # overise save
    def save(self, *args, **kwargs):
        super(ExerciseChoiceAnswer, self).save(*args, **kwargs) 
        data= xlrd.open_workbook(settings.BASE_DIR + self.file_excel.url) #open a file
        table = data.sheet_by_index(0) #Get a worksheet
        nrows = table.nrows #Rows
        ncols = table.ncols 
        self.num_rows = nrows - 1
        super().save(*args, **kwargs)  


class ExerciseArrange(models.Model):
    lesson = models.ForeignKey(Lesson,on_delete=models.CASCADE)
    type = models.ForeignKey(TypeExercise,on_delete=models.CASCADE)
    file_excel =  models.FileField(upload_to='exercise/word_arrange/', max_length=100,null=True)
    num_rows = models.PositiveSmallIntegerField(default=0,null=True)
       
   
    
    # overise save
    def save(self, *args, **kwargs):
        super(ExerciseArrange, self).save(*args, **kwargs) 
        data= xlrd.open_workbook(settings.BASE_DIR + self.file_excel.url) #open a file
        table = data.sheet_by_index(0) #Get a worksheet
        nrows = table.nrows #Rows
        ncols = table.ncols 
        self.num_rows = nrows - 1
        super().save(*args, **kwargs)

    def __str__(self):
        return '%s ,--- %s ,---%s : %s' % (self.lesson.chapter.course.title,self.lesson.chapter.title,self.lesson.get_titlesub_display(),self.type.title)
    
    
class ExerciseWordMissing(models.Model):
    lesson = models.ForeignKey(Lesson,on_delete=models.CASCADE)   
    type = models.ForeignKey(TypeExercise,on_delete=models.CASCADE)
    file_excel =  models.FileField(upload_to='exercise/word_missing/', max_length=100,null=True)
    num_rows = models.PositiveSmallIntegerField(default=0,null=True)
    def __str__(self):
        return '%s ,--- %s ,---%s : %s' % (self.lesson.chapter.course.title,self.lesson.chapter.title,self.lesson.get_titlesub_display(),self.type.title)
    
    # overise save
    def save(self, *args, **kwargs):
        super(ExerciseWordMissing, self).save(*args, **kwargs) 
        data= xlrd.open_workbook(settings.BASE_DIR + self.file_excel.url) #open a file
        table = data.sheet_by_index(0) #Get a worksheet
        nrows = table.nrows #Rows
        ncols = table.ncols 
        self.num_rows = nrows - 1
        super().save(*args, **kwargs)
  

class ViolympicEndCourse(models.Model):
    title = models.CharField(default='',max_length=60)
    course = models.ForeignKey(Course,on_delete=models.CASCADE)
    file_excel =  models.FileField(upload_to='violympic/', max_length=100)

    def __str__(self):
        return '%s -- %s' % (self.title,self.course.title)

templates/course/course.html
{% extends "pages/base.html" %} 
{% block title %} {{cs.title}} {% endblock %}
{% load humanize %}
{% load course_tag %}
{%block content%} 
{%load static%}
<!--? slider Area Start-->
  <section class="slider-area slider-area2">
            <div class="slider-active">
                <!-- Single Slider -->
                <div class="single-slider slider-height2">
                    <div class="container">
                        <div class="row">
                            <div class="col-xl-8 col-lg-11 col-md-12">
                                <div class="hero__caption hero__caption2">
                                    <h1 data-animation="bounceIn" data-delay="0.2s">{{cs.title}}</h1>
                                    <!-- breadcrumb Start-->
                                    <nav aria-label="breadcrumb">
                                        <ol class="breadcrumb">
                                            <li class="breadcrumb-item"><a href="{%url 'home:index'%}">Home</a></li>
                                            <li class="breadcrumb-item"><a href="{{request.get_full_path}}">{{cs.title}}</a></li> 
                                        </ol>
                                    </nav>
                                    <!-- breadcrumb End -->
                                </div>
                            </div>
                        </div>
                    </div>          
                </div>
            </div>
  </section>
  <div class="container container-h-100 pb-padding area_enghome mt-30">
    <div class="khta_banner">
      <img src="{{cs.course_banner.url}}" alt="" />
      <h1 class="course_title">{{cs.title}}</h1>
    </div>
    <div class="eng_infor">
      <p>
        {{cs.description}}<br>
        
      </p>
    </div>
    <div class="eng_bgscore">
      {%if std_course%}
        <div class="eng_verline"></div>
        <div class="eng_arright">
          <div class="eng_arscore">
            <div class="eng_text">Tổng điểm:</div>
            <div class="eng_bgs">
            
            {% sum_score_course user.id cs.id as sumScoreCourse%}
            {% total_score_course user.id cs.id as toalScoreCourse%}
            {% persent_progress_chap sumScoreCourse toalScoreCourse as persentProgresCourse%}
              <div class="ehhirs_yourscore">{{sumScoreCourse}}</div>
              <div class="ehhirs_line"></div>
              <div class="ehhirs_sumscore">{{toalScoreCourse}}</div>
            </div>
          </div>
          <div class="ehhir_tpersent">
            Tiến trình hoàn thành:
            <span class="ehhir_persent">{{persentProgresCourse}}%</span>
          </div>
          <div class="ehhir_aripersent">
            <div class="ehhir_ipersent" style="width: {{persentProgresCourse}}%"></div>
          </div>
        </div> 
      
      {%else%}
      <div class="buy-course-detail">
            <div class="block-price">
              <p>
              Giảm giá:
              <span>
                {%if cs.discounted_price == 0%}
                    Khóa học chưa có giảm giá
                {%else%}
                  <span class="discount-price2">Giảm <span style="font-weight:600;color:#000;font-size:16px;">{{cs.discounted_price}}%</span> khi mua khóa học</span>
                {%endif%}
              </span>
              </p>
            </div>
          
            <div class="block-btn text-center">
              <a href="{% url 'order:register_course' cs.id %}" class="btn-cart-course btn-add_cart">
                  <i class="fa fa-cart-plus" aria-hidden="true"></i>
                  Mua khóa học ngay</a>
              </a>
              
              <p>Hoàn tiền trong 7 ngày nếu không hài lòng</p>
            </div>
            <div class="block-btn">
               <ul class="des_buy_course_detail">
                  <li><i class="ti-book"></i>Số chương: <span>{{count_chap}} chương</span></li>
                  <li><i class="ti-slice"></i>Bài tập: <span>Đa dạng</span></li>
                  <li><i class="ti-game"></i>Trò chơi: <span>Phong phú</span></li>
               </ul>
            </div>
         
      </div>
     {%endif%}
      
    </div>
    <!--List lesson-->
    
    <!--Start list-->
    <div class="accordionExample">  
      {% for item in chap%}
      <div class="container_accord">
      {% lesson_of_chapter item.id as lesson_of_chapter%}
          {% total_score_chapter user.id cs.id item.id as totalScore%}
          {% sum_score_chapter user.id cs.id item.id as sumScore%}
          <div class="label_accord">
            <div class="counter_chapter__">
              <span class="text_counter_course">{{forloop.counter}}</span>
            </div>
              
            <div class="kphml_name">
                <div class="kphmln_ten">{{item.title}}</div>
                <div class="kphmln_tvi">{{item.title_vi}}</div>
            </div>
            <div class="persent_progress_chapter__ d-flex-center">
            
            {% persent_progress_chap sumScore totalScore as persent_your%}
                <span>{{persent_your}} %</span>
            </div>
            <div class="area__score_ d-flex-center">
              
               <span class="yourscore__">{{sumScore}}</span>/<span class="total__score_">{{totalScore}}</span>
            </div>
          </div>
          <!--Content accord -->
          <div class="content__ content_h_auto">
          {%for item2 in lesson_of_chapter%}
            {%if learn_course is None %} <!--Neu chua mua khoa hoc-->
                    {%if item2.icon == 1%}
                        <div class="kphmlc_part kphmlc_part_one">
                    {%elif item2.icon == 2%}
                        <div class="kphmlc_part kphmlc_part_two">
                    {%elif item2.icon == 3%}
                        <div class="kphmlc_part kphmlc_part_three">
                    {%elif item2.icon == 4%}
                        <div class="kphmlc_part kphmlc_part_four">
                    {%endif%} 
            {%else%}
                {% day_left learn_course.finish_date as dayLeft %}
                                                    
                {%if dayLeft < 0%} <!-- Het thoi gian vip ma chua mua them vip-->
                    {%if item2.icon == 1%}
                        <div class="kphmlc_part kphmlc_part_one">
                    {%elif item2.icon == 2%}
                        <div class="kphmlc_part kphmlc_part_two">
                    {%elif item2.icon == 3%}
                        <div class="kphmlc_part kphmlc_part_three">
                    {%elif item2.icon == 4%}
                        <div class="kphmlc_part kphmlc_part_four">
                    {%endif%}                                         
                {%else%} <!-- Con thoi gian hoc VIP-->
                    {%if item2.icon == 1%}
                        <a href="{% url 'course:detaillesson' cs.id item2.id%}" class="kphmlc_part kphmlc_part_one">
                    {%elif item2.icon == 2%}
                        <a href="{% url 'course:detaillesson' cs.id item2.id%}" class="kphmlc_part kphmlc_part_two">
                    {%elif item2.icon == 3%}
                        <a href="" class="kphmlc_part kphmlc_part_three">
                    {%elif item2.icon == 4%}
                        <a href="" class="kphmlc_part kphmlc_part_four">
                    {%endif%}
                {%endif%}
            {%endif%}
         
                    <div class="kphmlcp_arname">
                      <div class="kphmlcpn_icon">
                        <img src="/media/{{item2.get_icon_display}}" />
                      </div>
                      <div class="kphmlcpn_ten">{{item2.get_titlesub_display}}</div>
                      <div class="kphmlcpn_tvi">{{item2.get_titlesub_vi_display}}</div>
                    </div>
                    <div class="kphmlcp_arlink">
                      <div class="kphmlcpl_text">{{item2.description}}</div>
                      <div class="kphmlcpl_tvi">{{item2.description_vi}}</div>
                    </div>
              {%if learn_course is None %} <!--Neu chua mua khoa hoc-->
                   </div>
              {%else%}
                {% day_left learn_course.finish_date as dayLeft %}            
                {%if dayLeft < 0%} <!-- Het thoi gian vip ma chua mua them vip-->
                   </div>
                {%else%} <!-- Con thoi gian hoc VIP-->
                   </a>
                {%endif%}
              {%endif%}
                </a>
            {%endfor%}
          </div>
          
      </div>
      {% endfor %}   
      <!--Violym pic end course-->
      {%if vio_one%}
      
      <div class="container_accord">
          <div class="label_accord">
            <div class="kphmln_icon_pre"></div>
            <div class="kphml_name">
              <div class="kphmln_ten">{{vio_one.title}}</div>
              <div class="kphmln_tvi">Ôn tập</div>
            </div>
          </div>
          <div class="content__ content_h_auto prl-padding">
              <div class="detail_course_ins_vio">Phần này sẽ giúp các em ôn tập lại tất cả kiến thức của khóa học lớp {{vio_one.course.id}}.</div>
              {%if learn_course is None %} <!--Neu chua mua khoa hoc-->
                   <span class="prev_vio_button" >
                      vào làm bài
                    </span>
              {%else%}
                {% day_left learn_course.finish_date as dayLeft %}            
                {%if dayLeft < 0%} <!-- Het thoi gian vip ma chua mua them vip-->
                    <span class="prev_vio_button" >
                      vào làm bài
                    </span>
                {%else%} <!-- Con thoi gian hoc VIP-->
                    <a class="prev_vio_button" href="{% url 'course:violympic_end_course' vio_one.course.id vio_one.id %}">
                      vào làm bài
                    </a>
                {%endif%}
              {%endif%}
             
          </div>
      </div>
     
      {%endif%}  
    </div>
    <!--End list-->

  </div>


{%endblock%}