course/urls.py
from django import urls
from django.urls import path
from .import views

app_name = 'course'

urlpatterns = [
    path('<int:course_id>/',views.Deatail_Course,name='detailcourse'),  
    path('<int:course_id>/<int:lesson_id>/game/1/<int:num_scores>/<int:is_doing>/<int:is_get>/',views.get_post_data_game_word_card,name='lesson_game_card'),
    path('<int:course_id>/<int:lesson_id>/game/2/<int:num_scores>/<int:is_doing>/<int:is_get>/',views.get_post_data_game_golden_fish,name='lesson_game_golden_fish'),
    path('<int:course_id>/<int:lesson_id>/',views.View_Detail_Lesson,name='detaillesson'),
    path('<int:course_id>/violympic-end-course/<int:vio_one_id>/',views.Violympic_End_Course,name='violympic_end_course'),
    path('<int:course_id>/<int:lesson_id>/exercise/3/<int:num_scores>/<int:is_doing>/<int:is_get>/',views.get_post_data_exercise_arrange,name='lesson_arrange'),
    path('<int:course_id>/<int:lesson_id>/exercise/2/<int:num_scores>/<int:is_doing>/<int:is_get>/',views.get_post_data_exercise_missing,name='lesson_missing'),
    path('<int:course_id>/<int:lesson_id>/exercise/1/<int:num_scores>/<int:is_doing>/<int:is_get>/',views.get_post_data_exercise_choice,name='lesson_choice'),  
]

home/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import LogoutView

app_name = 'home'

urlpatterns = [
    path('',views.index,name='index'),
    path('about/',views.About,name='about'),
    path('contact/',views.Contact,name='contact'),
    
    path('search/',views.search_text,name='search-text'),
    path('login/',views.loginUser.as_view(),name='loginUser'),
    path('register/',views.registerUser.as_view(),name='registerUser'),
    path('register-teacher/',views.registerTeacher.as_view(),name='registerTeacher'),
    path('logout/',LogoutView.as_view(),name='logoutUser'),
]

learnEnglish/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
#

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('home.urls')),
    path('course/',include('course.urls')),
    path('order/',include('order.urls')),
    path('payment/',include('payment.urls')),
    path('dashboard/',include('usermember.urls')),
    path('competition/',include('competition.urls')),
   
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/models.py
from django.db import models

# Create your models here.

home/forms.py
from django import forms

class registerForm(forms.Form):
    username = forms.CharField(max_length=15)
    email = forms.EmailField()
    password = forms.CharField(max_length=20,widget=forms.PasswordInput)

class loginForm(forms.Form):
    username = forms.CharField(max_length=15)
    password = forms.CharField(max_length=20,widget=forms.PasswordInput)

home/views.py
from django.http.response import JsonResponse
from django.shortcuts import redirect, render
from .forms import registerForm, loginForm
from django.views import View
from django.contrib.auth.models import User
from usermember.models import MyUser
from django.contrib.auth import authenticate, login,logout
from django.http import HttpResponse,HttpResponseRedirect
from course.models import Chapter, Course
from usermember.models import Student,Teacher
from django.contrib.auth.mixins import LoginRequiredMixin

# Create your views here.


def index(request):
    course = Course.objects.all()
    teacher = Teacher.objects.filter(active=True)[:5]
    context = {
        'course':course,
       'teacher':teacher,
    }
    return render(request,'home/index.html',context)

def About(request):
    return render(request, 'home/about.html')

def Contact(request):
    return render(request, 'home/contact.html')

def search_text(request):
    if 'q' in request.GET:
        q = request.GET['q']
        if q == '':
            return redirect('home:index')
        else:
            # co du lieu
              
            data_search = Chapter.objects.filter(title__icontains=q)
            count_search = Chapter.objects.filter(title__icontains=q).count()
            
            return render(request,'home/search.html',{'result':q,'data_search':data_search,'count_search':count_search})
    else:
        return redirect('home:index')

class registerTeacher(LoginRequiredMixin,View):   
    login_url = '/login/'
    def get(self, request):
        return render(request,'home/register_teacher.html')

    def post(self, request):
        print(request.POST)
        fullname = request.POST['fullname_id']
        title = request.POST['title_id']
        phone = request.POST['phone_id']
        email = request.POST['email_id']
        address = request.POST['address_id']
        linkVideo = request.POST['linkVideo_id']
        linkFB = request.POST['linkFB_id']
        experience = request.POST['experience_id']

        check_is_student = Student.objects.filter(user_id=request.user.id)
        check_is_teacher = Teacher.objects.filter(user_id=request.user.id)

        if check_is_student:
            return JsonResponse({'status': 500})

        if check_is_teacher:
            return JsonResponse({'status': 400})
        try:
            teacher = Teacher.objects.create(
                user=request.user,
                fullname=fullname,
                title=title,
                phone=phone,
                email=email,
                address=address,
                link_video=linkVideo,
                link_fb=linkFB,
                experience=experience
            )

            return JsonResponse({'status': 200})
        except:
            return JsonResponse({'status': 300})
    
class registerUser(View):
    def get(self, request):
        return render(request,'home/register.html')

    def post(self, request):
        username = request.POST['username']
        email = request.POST['email']
        password = request.POST['password']
        repassword = request.POST['repassword']
        uN = ''
        pW = ''
        lenreP = ''
        reP = ''
        if len(username) < 5:
            uN = 'Tên đăng nhập nhỏ hơn 5 ký tự'
        if len(password) < 6:
            pW = 'Mật khẩu nhỏ hơn 6 ký tự'
        if len(repassword) < 6:
            lenreP = 'Mật khẩu nhỏ hơn 6 ký tự'
        if repassword != password:
            reP = 'Nhập lại mật khẩu không trùng khớp'
        context = {'uN':uN,'pW':pW,'lenreP':lenreP,'reP':reP}
        if len(username) >= 5 and len(password) >= 6 and len(repassword) >= 6 and repassword == password:
            user = MyUser(username=username,email=email,password=password)
            suse = 'Đăng ký tài khoản thành công'
            
            return render(request,'home/register.html',{'suse':suse})           
        else:
            return render(request,'home/register.html',context)

class loginUser(View):
    def get(self, request):    
        return render(request,'home/login.html')
    def post(self,request):
        username = request.POST['username'] 
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)  
            return redirect('usermember:dashboard_user',name_url='course')
        else:          
            context = {'mess':'Tên đăng nhập hoặc mật khẩu không đúng','uN':username,'pW':password}
            return render(request,'home/login.html',context)

def logoutUser(request):
    logout(request)


templates/home/index.html
{% extends "pages/base.html" %}

{% load humanize %}
{% load nav_tag %}
{% load static %}
{% block title %}
Trang chủ
{% endblock %}

 
{% block content%}
<!--? slider Area Start-->
        <section class="slider-area ">
            <div class="slider-active">
                <!-- Single Slider -->
                <div class="single-slider slider-height d-flex align-items-center">
                    <div class="container">
                        <div class="row">
                            <div class="col-xl-6 col-lg-7 col-md-12">
                                <div class="hero__caption">
                                    <h1 data-animation="fadeInLeft" data-delay="0.2s">Nền tảng học tập<br> trực tuyến</h1>
                                    <p data-animation="fadeInLeft" data-delay="0.4s">Xây dựng được các kỹ năng từ những giảng viên giàu kinh nghiệm, được đào tạo bài bản.</p>
                                    <a href="#" class="btn hero-btn" data-animation="fadeInLeft" data-delay="0.7s">Tham gia ngay</a>
                                </div>
                            </div>
                        </div>
                    </div>          
                </div>
            </div>
        </section>
        <!-- ? services-area -->
        <div class="services-area">
            <div class="container">
                <div class="row justify-content-sm-center">
                    <div class="col-lg-4 col-md-6 col-sm-8">
                        <div class="single-services mb-30">
                            <div class="features-icon">
                                <img src="{% static 'img/icon/icon1.svg' %}" alt="">
                            </div>
                            <div class="features-caption">
                                <h3>5+ Khóa học</h3>
                                <p>Quá trình tự động hóa tất cả các tác vụ trang web của bạn.</p>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-4 col-md-6 col-sm-8">
                        <div class="single-services mb-30">
                            <div class="features-icon">
                                <img src="{% static 'img/icon/icon2.svg' %}" alt="">
                            </div>
                            <div class="features-caption">
                                <h3>Chuyên gia hướng dẫn</h3>
                                <p>Quá trình tự động hóa tất cả các tác vụ trang web của bạn.</p>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-4 col-md-6 col-sm-8">
                        <div class="single-services mb-30">
                            <div class="features-icon">
                                <img src="{% static 'img/icon/icon3.svg' %} " alt="">
                            </div>
                            <div class="features-caption">
                                <h3>Kiểm soát thời gian</h3>
                                <p>Quá trình tự động hóa tất cả các tác vụ trang web của bạn.</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Courses area start -->
        <div class="courses-area section-padding40 fix">
            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-xl-7 col-lg-8">
                        <div class="section-tittle text-center mb-55">
                            <h2>Khóa học nổi bật</h2>
                        </div>
                    </div>
                </div>
                <div class="courses-actives">
                {%for item in course%}
                    <!-- Single -->
                    <div class="properties pb-20">
                        <div class="properties__card">
                            <div class="properties__img overlay1">
                                <a href="{% url 'course:detailcourse' item.id %}"><img src="{{item.course_img.url}}" al t=""></a>
                            </div>
                            <div class="properties__caption">
                                <p>Giảng viên có kinh nghiệm</p>
                                <h3><a href="{{item.course_img.url}}">{{item.title}}</a></h3>
                                <p>
                                    {{item.excerpt}}
                                </p>
                                <div class="properties__footer d-flex justify-content-between align-items-center">          
                                    <div class="price">
                                        <span> {{item.price_month|intcomma }} </span><sub>/tháng</sub>
                                    </div>
                                </div>
                                <a href="{% url 'course:detailcourse' item.id %}" class="border-btn border-btn2">Xem chi tiết</a>
                            </div>

                        </div>
                    </div>
                    <!-- Single -->
                {%endfor%} 
                </div>
            </div>
        </div>
        <!-- Courses area End -->
        <!--? About Area-1 Start -->
        <section class="about-area1 fix pt-10">
            <div class="support-wrapper align-items-center">
                <div class="left-content1">
                    <div class="about-icon">
                        <img src="{% static 'img/icon/about.svg' %}" alt="">
                    </div>
                    <!-- section tittle -->
                    <div class="section-tittle section-tittle2 mb-55">
                        <div class="front-text">
                            <h2 class="">Học các kỹ năng mới trực tuyến với các nhà giáo dục hàng đầu</h2>
                            <p>Khám phá các công cụ và kỹ thuật để tương tác hiệu quả với trẻ em.</p>
                        </div>
                    </div>
                    <div class="single-features">
                        <div class="features-icon">
                            <img src="{% static 'img/icon/right-icon.svg' %}" alt="">
                        </div>
                        <div class="features-caption">
                            <p>Các kỹ thuật để tương tác hiệu quả với trẻ em.</p>
                        </div>
                    </div>
                    <div class="single-features">
                        <div class="features-icon">
                            <img src="{% static 'img/icon/right-icon.svg' %} " alt="">
                        </div>
                        <div class="features-caption">
                            <p>Tham gia cùng hàng triệu người từ khắp nơi trên thế giới cùng nhau học tập.</p>
                        </div>
                    </div>

                    <div class="single-features">
                        <div class="features-icon">
                            <img src="{% static 'img/icon/right-icon.svg' %} " alt="">
                        </div>
                        <div class="features-caption">
                            <p>Học trực tuyến dễ dàng và tự nhiên.</p>
                        </div>
                    </div>
                </div>
                <div class="right-content1">
                    <!-- img -->
                    <div class="right-img">
                        

                        <div class="video-icon" >
                            <a class="popup-video btn-icon" href="https://www.youtube.com/watch?v=up68UAfH0d0"><i class="fas fa-play"></i></a>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <!-- About Area End -->
       <!--Should learn at website-->
       <section class="section-padding40 fix">
            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-xl-7 col-lg-8">
                        <div class="section-tittle text-center mb-55">
                            <h2>3 LÝ DO BẠN NÊN HỌC ONLINE TẠI WEBSITE</h2>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4 pdm-No">
                        <div class="reason-4">
                            <div class="img-reason"><img class="img-responsive lazy" alt="" src="https://unica.vn/media/images/icon-ts-1.png" style=""></div>
                            <div class="txt-reason">Giảng viên uy tín
                                <span>Bài giảng chất lượng</span>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4 pdm-No">
                        <div class="reason-4">
                            <div class="img-reason"><img class="img-responsive lazy" alt="" src="https://unica.vn/media/images/icon-ts-2.png" style=""></div>
                            <div class="txt-reason">Thanh toán 1 lần
                                <span>Học mãi mãi</span>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4 pdm-No">
                        <div class="reason-4">
                            <div class="img-reason"><img class="img-responsive lazy" alt="" src="https://unica.vn/media/images/icon-ts-3.png" style=""></div>
                            <div class="txt-reason">Học trực tuyến
                                <span>Hỗ trợ trực tiếp</span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
       <!--End shoild learn-->
        <!--? Teacher -->
        <section class="team-area section-padding40 fix">
            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-xl-7 col-lg-8">
                        <div class="section-tittle text-center mb-55">
                            <h2>GIẢNG VIÊN TIÊU BIỂU</h2>
                        </div>
                    </div>
                </div>
                <div class="team-active">
                    {%for tItem in teacher%}
                    <div class="single-cat text-center">
                        <div class="cat-icon">
                            <img src="{{tItem.user.std_img.url}}" alt="">
                        </div>
                        <div class="cat-cap">
                            <h5><a href="services.html">{{tItem.fullname}}</a></h5>
                            <p>{{tItem.title}}</p>
                        </div>
                    </div>
                    {%endfor%}
                </div>
            </div>
        </section>
        <!-- Services End -->
        <!--? About Area-2 Start -->
        <section class="fix pt-padding">
            <div class="container-fluid come-teacher">
                <div class="container">
                    <div class="text-center text-center-v2 form-group">
                        <div class="txt-bc-gv"><p class="text-white">Trở thành Giảng viên OMG</p></div>
                        <p class="text-white2">Hơn 100 giảng viên đã có khóa học trên OMG</p>
                        <a href="{% url 'home:registerTeacher' %}" class="text-bold">Đăng ký ngay</a>
                    </div>
                
            </div>
        </section>
        <!-- About Area End -->
{%endblock%}

templates/home/login.html
<!DOCTYPE html>
<html class="no-js" lang="zxx">
<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>Đăng nhập thành viên</title>
    {% load static%}
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'img/favicon.ico' %}">
    
    <!-- CSS here -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href=" {% static 'css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/slicknav.css' %}">
    <link rel="stylesheet" href="{% static 'css/flaticon.css' %}">
    <link rel="stylesheet" href="{% static 'css/progressbar_barfiller.css' %}">
    <link rel="stylesheet" href="{% static 'css/gijgo.css' %}">
    <link rel="stylesheet" href="{% static 'css/animate.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/animated-headline.css' %}">
    <link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}">
    <link rel="stylesheet" href="{% static 'css/fontawesome-all.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/themify-icons.css' %}">
    <link rel="stylesheet" href="{% static 'css/slick.css' %}">
    <link rel="stylesheet" href="{% static 'css/nice-select.css' %}">
    <link rel="stylesheet" href="{% static 'css/style_template.css' %}">
    
</head>
<body>
    <!-- ? Preloader Start -->
    <div id="preloader-active">
        <div class="preloader d-flex align-items-center justify-content-center">
            <div class="preloader-inner position-relative">
                <div class="preloader-circle"></div>
                <div class="preloader-img pere-text">
                     <img src="{% static 'img/logo/loder.png' %}" alt="">
                </div>
            </div>
        </div>
    </div>
    <!-- Preloader Start-->

    <video autoplay muted loop id="myVideoFullScreen">
        <source src="{% static 'img/login-bg.mp4' %}" type="video/mp4">
    </video>
    <main class="login-body">
        <!-- Login User -->
        <form class="form-default" action="{% url 'home:loginUser' %}" method="POST">
            {% csrf_token %}
            <div class="login-form">
                <!-- logo-login -->
                <div class="logo-login">
                    <a href="{% url 'home:index' %}"><img src="{% static 'img/logo/loder.png' %}" alt=""></a>
                </div>
                <h2>Login Here</h2>
                {% if not mess %}
                {% else %}
                   <!-- Error Alert -->
                    <div class="alert alert-danger alert-dismissible fade show">
                        <strong>Error!</strong> {{mess}}
                        <button type="button" class="close" data-bs-dismiss="alert"> <span aria-hidden="true">&times;</span></button>
                    </div>
                   
                {% endif %}
                <div class="form-input">
                    <label for="name">User name</label>
                    <input  type="text" name="username"
                        maxlength="15"                       
                        {% if not uN %}
                        {% else %}
                            value={{uN}}
                        {% endif %}
                        required 
                        placeholder="User name">
                </div>
                
                <div class="form-input">
                    <label for="name">Password</label>
                    <input type="password" name="password"
                        maxlength="20"
                        {% if not pW %}
                        {% else %}
                            value={{pW}}
                        {% endif %}
                        required placeholder="Password">
                </div>
                <div class="form-input pt-30">
                    <input type="submit" name="submit" value="login">
                </div>
                
                <!-- Forget Password -->
                <a href="#" class="forget">Forget Password</a>
                <!-- Forget Password -->
                <a href="{% url 'home:registerUser'%}" class="registration">Registration</a>
            </div>
        </form>
        <!-- /end login form -->
    </main>


   <!-- JS here -->
<script src="{% static 'js/vendor/modernizr-3.5.0.min.js'%}"> </script>
<!-- Jquery, Popper, Bootstrap -->
<script src="{% static 'js/vendor/jquery-1.12.4.min.js'%}"></script>
<script src="{% static 'js/popper.min.js'%}"></script>
<script src="{% static 'js/bootstrap.min.js'%}"></script>
<!-- Jquery Mobile Menu -->
<script src="{% static 'js/jquery.slicknav.min.js'%}"></script>

<!-- Jquery Slick , Owl-Carousel Plugins -->
<script src="{% static 'js/owl.carousel.min.js'%}"></script>
<script src="{% static 'js/slick.min.js'%}"></script>
<!-- One Page, Animated-HeadLin -->
<script src="{% static 'js/wow.min.js'%}"></script>
<script src="{% static 'js/animated.headline.js'%}"></script>
<script src="{% static 'js/jquery.magnific-popup.js'%}"></script>

<!-- Date Picker -->
<script src="{% static 'js/gijgo.min.js'%}"></script>
<!-- Nice-select, sticky -->
<script src="{% static 'js/jquery.nice-select.min.js'%}"></script>
<script src="{% static 'js/jquery.sticky.js'%}"></script>
<!-- Progress -->
<script src="{% static 'js/jquery.barfiller.js'%}"></script>

<!-- counter , waypoint,Hover Direction -->
<script src="{% static 'js/jquery.counterup.min.js'%}"></script>
<script src="{% static 'js/waypoints.min.js'%}"></script>
<script src="{% static 'js/jquery.countdown.min.js'%}"></script>
<script src="{% static 'js/hover-direction-snake.min.js'%}"></script>

<!-- contact js -->
<script src="{% static 'js/contact.js'%}"></script>
<script src="{% static 'js/jquery.form.js'%}"></script>
<script src="{% static 'js/jquery.validate.min.js'%}"></script>
<script src="{% static 'js/mail-script.js'%}"></script>
<script src="{% static 'js/jquery.ajaxchimp.min.js'%}"></script>

<!-- Jquery Plugins, main Jquery -->	
<script src="{% static 'js/plugins.js'%}"></script>
<script src="{% static 'js/main.js'%}"></script>
<script src="{% static 'js/app.js'%}"></script>
<script src="{% static 'js/bootstrap.bundle.min.js'%}"></script>

</body>
</html>

templates/home/register.html
<!DOCTYPE html>
<html class="no-js" lang="zxx">
<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>Đăng ký thành viên</title>
    {% load static%}
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'img/favicon.ico' %}">
    
    <!-- CSS here -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href=" {% static 'css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/slicknav.css' %}">
    <link rel="stylesheet" href="{% static 'css/flaticon.css' %}">
    <link rel="stylesheet" href="{% static 'css/progressbar_barfiller.css' %}">
    <link rel="stylesheet" href="{% static 'css/gijgo.css' %}">
    <link rel="stylesheet" href="{% static 'css/animate.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/animated-headline.css' %}">
    <link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}">
    <link rel="stylesheet" href="{% static 'css/fontawesome-all.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/themify-icons.css' %}">
    <link rel="stylesheet" href="{% static 'css/slick.css' %}">
    <link rel="stylesheet" href="{% static 'css/nice-select.css' %}">
    <link rel="stylesheet" href="{% static 'css/style_template.css' %}">
    
</head>
<body>
    <!-- ? Preloader Start -->
    <div id="preloader-active">
        <div class="preloader d-flex align-items-center justify-content-center">
            <div class="preloader-inner position-relative">
                <div class="preloader-circle"></div>
                <div class="preloader-img pere-text">
                     <img src="{% static 'img/logo/loder.png' %}" alt="">
                </div>
            </div>
        </div>
    </div>
    <!-- Preloader Start-->

    <video autoplay muted loop id="myVideoFullScreen">
        <source src="{% static 'img/login-bg.mp4' %}" type="video/mp4">
    </video>
    <main class="login-body">
        <!-- Login User -->
        <form class="form-default" action="{% url 'home:registerUser' %}" method="POST">
            {% csrf_token %}
            <div class="login-form">
                <!-- logo-login -->
                <div class="logo-login">
                    <a href="{% url 'home:index' %}"><img src="{% static 'img/logo/loder.png' %}" alt=""></a>
                </div>
                <h2>Registration Here</h2>
                {% if not suse %}
                {% else %}
                   <!-- Success  Alert -->
                    <div class="alert alert-success  alert-dismissible fade show">
                        <strong>Success !</strong> {{suse}}
                        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                    </div>
                   
                {% endif %}
                <div class="form-input">
                  <label for="name">User name</label>
                  <input  type="text" name="username" placeholder="User name">
                </div>
                <div class="form-input">
                    <label for="name">Email Address</label>
                    <input type="email" name="email" placeholder="Email Address">
                </div>
                <div class="form-input">
                    <label for="name">Password</label>
                    <input type="password" name="password" placeholder="Password">
                </div>
                <div class="form-input">
                    <label for="name">Confirm Password</label>
                    <input type="password" name="repassword" placeholder="Confirm Password">
                </div>
                <div class="form-input pt-30">
                    <input type="submit" name="submit" value="Registration">
                </div>
                
                
                <!-- Have a account -->
                <a href="{% url 'home:loginUser'%}" class="registration">Login</a>
            </div>
        </form>
        <!-- /end login form -->
    </main>


   <!-- JS here -->
<script src="{% static 'js/vendor/modernizr-3.5.0.min.js'%}"> </script>
<!-- Jquery, Popper, Bootstrap -->
<script src="{% static 'js/vendor/jquery-1.12.4.min.js'%}"></script>
<script src="{% static 'js/popper.min.js'%}"></script>
<script src="{% static 'js/bootstrap.min.js'%}"></script>
<!-- Jquery Mobile Menu -->
<script src="{% static 'js/jquery.slicknav.min.js'%}"></script>

<!-- Jquery Slick , Owl-Carousel Plugins -->
<script src="{% static 'js/owl.carousel.min.js'%}"></script>
<script src="{% static 'js/slick.min.js'%}"></script>
<!-- One Page, Animated-HeadLin -->
<script src="{% static 'js/wow.min.js'%}"></script>
<script src="{% static 'js/animated.headline.js'%}"></script>
<script src="{% static 'js/jquery.magnific-popup.js'%}"></script>

<!-- Date Picker -->
<script src="{% static 'js/gijgo.min.js'%}"></script>
<!-- Nice-select, sticky -->
<script src="{% static 'js/jquery.nice-select.min.js'%}"></script>
<script src="{% static 'js/jquery.sticky.js'%}"></script>
<!-- Progress -->
<script src="{% static 'js/jquery.barfiller.js'%}"></script>

<!-- counter , waypoint,Hover Direction -->
<script src="{% static 'js/jquery.counterup.min.js'%}"></script>
<script src="{% static 'js/waypoints.min.js'%}"></script>
<script src="{% static 'js/jquery.countdown.min.js'%}"></script>
<script src="{% static 'js/hover-direction-snake.min.js'%}"></script>

<!-- contact js -->
<script src="{% static 'js/contact.js'%}"></script>
<script src="{% static 'js/jquery.form.js'%}"></script>
<script src="{% static 'js/jquery.validate.min.js'%}"></script>
<script src="{% static 'js/mail-script.js'%}"></script>
<script src="{% static 'js/jquery.ajaxchimp.min.js'%}"></script>

<!-- Jquery Plugins, main Jquery -->	
<script src="{% static 'js/plugins.js'%}"></script>
<script src="{% static 'js/main.js'%}"></script>
<script src="{% static 'js/app.js'%}"></script>
<script src="{% static 'js/bootstrap.bundle.min.js'%}"></script>

</body>
</html>