competition/urls.py
from django.urls import path,re_path
from . import views

app_name = 'competition'

urlpatterns = [
    path('', views.ListRoomCompetition,name='list_room_competition'),
    path('init-room/', views.InitRoomCompetition,name='init_room_competition'),
    path('wait-<str:room_name>/', views.RoomWaitCompetition,name='await_room_competition'),
    path('play-<str:room_name>/', views.RoomPlayCompetition,name='room_play_competition'),
    path('history/', views.HistoryMemberCompete,name='history_member_competition'),
    path('ranking/', views.RankingCompetition,name='ranking_competition'),

    path('post-result-play/<str:room_name>/', views.Post_Result_Play,name='post_result_play'),

    path('ajax/GetRankByWeek/', views.GetRankByWeek,name='Get_Rank_By_Week'),
    path('post-init-room/', views.post_init_room,name='post_init_room'),
    path('get_method_post_join_room/', views.get_method_post_join_room,name='get_method_post_join_room'),
    path('get_method_post_quit_room/', views.get_method_post_quit_room,name='get_method_post_quit_room'),
    path('thidau/getMembersIdOnline/', views.get_post_list_friend_online,name='get_post_list_friend_online'),
    path('get_post_send_invite_to_room/', views.get_post_send_invite_to_room,name='get_post_send_invite_to_room'),
    path('post_wait_to_play_compete/', views.post_wait_to_play_compete,name='post_wait_to_play_compete'), 
]

home/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import LogoutView

app_name = 'home'

urlpatterns = [
    path('',views.index,name='index'),
    path('about/',views.About,name='about'),
    path('contact/',views.Contact,name='contact'),
    
    path('search/',views.search_text,name='search-text'),
    path('login/',views.loginUser.as_view(),name='loginUser'),
    path('register/',views.registerUser.as_view(),name='registerUser'),
    path('register-teacher/',views.registerTeacher.as_view(),name='registerTeacher'),
    path('logout/',LogoutView.as_view(),name='logoutUser'),
]

learnEnglish/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
#

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('home.urls')),
    path('course/',include('course.urls')),
    path('order/',include('order.urls')),
    path('payment/',include('payment.urls')),
    path('dashboard/',include('usermember.urls')),
    path('competition/',include('competition.urls')),
   
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/pages/base2.html
<!DOCTYPE html>
<html class="no-js" lang="zxx">
<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>{% block title%} {% endblock %}</title>
    {% load static%}
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'img/favicon.ico' %}">
    
    <!-- CSS here -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/flaticon.css' %}">
    <link rel="stylesheet" href="{% static 'css/animate.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/fontawesome-all.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/themify-icons.css' %}">
  
    <link rel="stylesheet" href="{% static 'css/ctr.css' %}">
    <link rel="stylesheet" href="{% static 'css/responsive.css' %}">
    
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/malihu-custom-scrollbar-plugin/3.1.5/jquery.mCustomScrollbar.min.css">
    <link rel="stylesheet" href="{% static 'css/chat.css' %}">
    
</head>

<body class="body-compete" >
    <div class="contest-real-time">
        <header>
            <div class="header-competition text-center">
                <a href="/" class="conpete-header-logo" style="position: relative;" onmouseover="(function(){$('#ctr-hl-hint').removeClass('hide');})()" onmouseout="(function(){$('#ctr-hl-hint').addClass('hide');})()">
                  <img src="{% static 'img/logo/logo.png' %}">
                  <div class="text-center ctr-hint-tooltip hide" id="ctr-hl-hint"><span>Quay về trang chủ Tiếng Anh</span></div>
                </a>
                <a href="{% url 'competition:list_room_competition' %}" class="click ctr-head-list"><i class="fa fa-home" style="font-size: 22px;" aria-hidden="true"></i> <span>Tìm phòng đấu</span></a>
                <a href="{%  url  'competition:ranking_competition' %}" class="click ctr-head-rank"><i class="fa fa-flag" aria-hidden="true"></i> <span>Bảng xếp hạng</span></a>
                <a href="{% url 'competition:history_member_competition' %}" class="click ctr-head-history"><i class="fa fa-hourglass-half" aria-hidden="true"></i> <span>Lịch sử thi đấu</span></a>
                <div class="btn-group ctr-head-intro">
                  <i class="fa fa-bookmark" aria-hidden="true"></i>
                  <div class="click inline-block dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false"> Hướng dẫn <span class="caret"></span> </div>
                  <ul class="dropdown-menu ctr-h-submenu-tutorial">
                    <span class="dropup"> <span class="caret"></span> </span>
                    <li class="click"><a href="/tutorial/join-room"><img class="head-sub-icon" src="{% static 'img/icon/ctr-hi-tutorial-icon-1.png' %}"> <span>Cách tham gia vào 1 phòng đấu</span></a></li>
                    <li class="click"><a href="/tutorial/init-room"><img class="head-sub-icon" src="{% static 'img/icon/ctr-hi-tutorial-icon-2.png' %}"> <span>Cách tạo một phòng đấu</span></a></li>
                    <li class="click"><a href="/tutorial/play"><img class="head-sub-icon" src="{% static 'img/icon/ctr-hi-tutorial-icon-3.png' %}"> <span>Trong phòng đấu</span></a></li>
                    <li class="click"><a href="/tutorial/score"><img class="head-sub-icon" src="{% static 'img/icon/ctr-hi-tutorial-icon-4.png' %}"> <span>Quy chế tính điểm thưởng</span></a></li>
                  </ul>
                </div>
                <!-- header-member-info -->
                <div class="inline-block ctr-head-member" id="ctr-header-member-info" style="position: relative;" >
                    <a class="ctr-h-avata" href="#">
                        <img class="ctr-h-avata-img" src="//data.tienganh123.com/images/member/noavatar.gif">
                        <img class="ab ctr-h-vip-img " src="{% static 'img/icon/ctr-vip-icon.png' %}" alt="">
                    </a>
                    <span class="ctr-hm-info text-left">
                        <span class="ctr-hmi-username">{{request.user.username}}</span><br>
                        <span class="ctr-hmi-achieve">
                        <span class="ctr-hmia-name newbie" style="color: #e69b57"><span class="ctr-r-name">Newbie</span></span>
                        <span class="ctr-hmia-star">
                                    <img src="{% static 'img/icon/ctr-star.png' %}">
                                </span>
                        </span>
                    </span>
                    <div class="ab size-zero" id="ctr-h-tooltip">
                        <ul class="list-group">
                        <li class="list-group-item ctr-h-point">
                            <p>Tổng điểm danh hiệu của bạn</p>
                            <div class="ctr-h-point-number">6</div>
                        </li>
                        <li class="list-group-item ctr-h-next-achive ">
                            <div style="margin-bottom: 5px;">Danh hiệu tiếp theo</div>
                            <div data-toggle="modal" href="#ctr-modal-appellation" class="ctr-h-next-avata" style="background-image: url('/static/img/head-newbie2.png')"></div>
                            <div class="text-center ctr-hmia-name">
                            <div class="inline-block newbie"><span class="ctr-r-name" style="color: #e69b57">Newbie</span></div>
                            </div>
                        </li>
                        <li class="list-group-item ctr-h-percent ">
                            <p>Tiến trình lên cấp</p>
                            <div class="progress">
                            <div class="progress-bar progress-bar-danger" role="progressbar" aria-valuenow="6" aria-valuemin="0" aria-valuemax="100" style="width: 6%;"></div>
                            <div class="progress-status"><span id="ctr-htp-score-number">6</span><span id="ctr-htp-score-total">/100</span></div>
                            </div>
                        </li>
                        <li class="list-group-item ctr-hmia-profile">
                            <a class="text-center ctr-hmia-profile-link" href="https://www.tienganh123.com/member/3307755#hocba">Về trang học bạ của tôi</a>
                        </li>
                        <li class="list-group-item ctr-hmia-logout" style="background-color: #d9534f;">
                            <a class="text-center ctr-hmia-logout-link" onclick="" href="{% url 'home:logoutUser' %}" style="color: #fff;">Thoát tài khoản</a>
                        </li>
                        </ul>
                    </div>
                </div>
            </div>
        </header>
         <main>
            {%block content%}

            {%endblock%}
        </main>
    </div>
    <audio id="cra_click" preload="auto" src="/static/audio/cra_click.mp3"></audio>

    

    <!-- Jquery, Popper, Bootstrap -->
    <script src="{% static 'js/vendor/jquery-1.12.4.min.js'%}"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.transit/0.9.12/jquery.transit.js" integrity="sha512-VRuRE7kBxU+JQr4R/7Y75cMMdeNnn5zDZRpT4qtEzAJXdMkmFPPGbS56Ch9/Lr2g5vnwN7PxtIdBvevTMVpnug==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/xlsx/0.17.3/xlsx.full.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="{% static 'js/bootstrap.min.js'%}"></script>
    <script src="{% static 'js/ctr.js'%}"></script>
    
    {% block scripts %}{% endblock scripts %}
</body>
</html>

templates/pages/empty.html
{%if is_enough == True%}
<div style="text-align:center;">
    <h2>Phòng đã đủ người rồi. Hãy chọn phòng khác</h2>
    <br>
    <a href="{% url 'competition:list_room_competition' %}" class="" style="text-decoration: none;padding: 10px 15px;background: orange;color: #fff;">
    <span>Tìm phòng đấu</span>
    </a>
</div>
{%endif%}