course/urls.py
from django import urls
from django.urls import path
from .import views

app_name = 'course'

urlpatterns = [
    path('<int:course_id>/',views.Deatail_Course,name='detailcourse'),  
    path('<int:course_id>/<int:lesson_id>/game/1/<int:num_scores>/<int:is_doing>/<int:is_get>/',views.get_post_data_game_word_card,name='lesson_game_card'),
    path('<int:course_id>/<int:lesson_id>/game/2/<int:num_scores>/<int:is_doing>/<int:is_get>/',views.get_post_data_game_golden_fish,name='lesson_game_golden_fish'),
    path('<int:course_id>/<int:lesson_id>/',views.View_Detail_Lesson,name='detaillesson'),
    path('<int:course_id>/violympic-end-course/<int:vio_one_id>/',views.Violympic_End_Course,name='violympic_end_course'),
    path('<int:course_id>/<int:lesson_id>/exercise/3/<int:num_scores>/<int:is_doing>/<int:is_get>/',views.get_post_data_exercise_arrange,name='lesson_arrange'),
    path('<int:course_id>/<int:lesson_id>/exercise/2/<int:num_scores>/<int:is_doing>/<int:is_get>/',views.get_post_data_exercise_missing,name='lesson_missing'),
    path('<int:course_id>/<int:lesson_id>/exercise/1/<int:num_scores>/<int:is_doing>/<int:is_get>/',views.get_post_data_exercise_choice,name='lesson_choice'),  
]

home/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import LogoutView

app_name = 'home'

urlpatterns = [
    path('',views.index,name='index'),
    path('about/',views.About,name='about'),
    path('contact/',views.Contact,name='contact'),
    
    path('search/',views.search_text,name='search-text'),
    path('login/',views.loginUser.as_view(),name='loginUser'),
    path('register/',views.registerUser.as_view(),name='registerUser'),
    path('register-teacher/',views.registerTeacher.as_view(),name='registerTeacher'),
    path('logout/',LogoutView.as_view(),name='logoutUser'),
]

learnEnglish/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
#

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('home.urls')),
    path('course/',include('course.urls')),
    path('order/',include('order.urls')),
    path('payment/',include('payment.urls')),
    path('dashboard/',include('usermember.urls')),
    path('competition/',include('competition.urls')),
   
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

order/urls.py
from django.urls import path
from .import views
app_name = 'order'

urlpatterns = [
    path('add-to-cart/<int:course_id>/<int:id_vip>/',views.add_to_cart,name='add-to-cart'),
    path('remove-item-from-cart/<int:course_id>/',views.remove_item_from_cart,name='remove-item-from-cart'),
    path('cart-view/',views.cart_view,name='cart'),
    path('register-course/<int:course_id>/',views.register_course,name='register_course'),
    
]

payment/urls.py
from django.urls import path
from .views import *

app_name = 'payment'

urlpatterns = [
    path('checkout/',CheckoutTemplateView.as_view(),name='checkout'),
    path('paypal/',paypalPaymentMethod.as_view(),name='paypal_payment'),
    path('success-payment-<int:id_order>/',success_payment,name='success_payment'),
    
]

order/models.py
from django.db import models
# from django.contrib.auth.models import User
from usermember.models import MyUser
from course.models import Course
from usermember.models import Student,StudentCourse
from django.core.validators import  MaxValueValidator, MinValueValidator 
from payment.models import BillingAddress
from datetime import datetime, timedelta
from usermember.createAuto import *
# Create your models here.


class OrderItem(models.Model):
    user = models.ForeignKey(MyUser,on_delete=models.CASCADE)
    purchased = models.BooleanField(default=False)
    item = models.ForeignKey(Course,on_delete=models.CASCADE)
    total_price = models.DecimalField(default=0,max_digits=8, decimal_places=0)
    vip_days = models.PositiveSmallIntegerField(default=0)
    is_lifetime = models.BooleanField(default=False) 
    

    def __str__(self):
        return f"{self.item.title} of {self.user.username} -- VIP: {self.vip_days} days"
    def get_total_item_price_month(self):
        return self.item.price_month
    
    def get_total_item_price_quarter(self):
        return self.item.price_quarter
    
    def get_total_item_price_year(self):
        return self.item.price_year
    
    def get_total_item_price_lifetime(self):
        return self.item.price_lifetime
    
    def get_total_discount_item_price_month(self):
        return (self.item.price_month*self.item.discounted_price)/100 
    
    def get_total_discount_item_price_quarter(self):
        return (self.item.price_quarter*self.item.discounted_price)/100 

    def get_total_discount_item_price_year(self):
        return (self.item.price_year*self.item.discounted_price)/100
     
    def get_total_discount_item_price_lifetime(self):
        return (self.item.price_lifetime*self.item.discounted_price)/100 

    def get_amount_saved_month(self):
        return self.get_total_item_price_month() - self.get_total_discount_item_price_month()
    
    def get_amount_saved_quarter(self):
        return self.get_total_item_price_quarter() - self.get_total_discount_item_price_quarter()
    
    def get_amount_saved_year(self):
        return self.get_total_item_price_year() - self.get_total_discount_item_price_year()
    
    def get_amount_saved_lifetime(self):
        return self.get_total_item_price_lifetime() - self.get_total_discount_item_price_lifetime()
    
class Order(models.Model):  
    PAYMENT_MOTHOD = (
        ('Cash on Delivery','Thanh toán khi nhận hàng'),
        ('PayPal','PayPal')
    )
    user = models.ForeignKey(MyUser,on_delete=models.CASCADE)
    items = models.ManyToManyField(OrderItem)
    start_date = models.DateTimeField(auto_now_add=True)
    ordered_date = models.DateTimeField()
    ordered = models.BooleanField(default=False) 
    payment_method = models.CharField(max_length=30,choices=PAYMENT_MOTHOD,default='Cash on Delivery')
    billing_address = models.ForeignKey(BillingAddress,on_delete=models.SET_NULL,null=True,blank=True)
    
    def __str__(self):
        return self.user.username
    
    def get_totals(self):
        total = 0
        for order_item in self.items.all():
             total += order_item.total_price
        return total

class OrderCashOnDelivery(models.Model):
    STATUS_CHOICE = (
        ('A','Chưa duyệt đơn hàng'),
        ('B','Đã duyệt đơn hàng'),
        ('C','Nhân viên đang đến'),
        ('D','Đã thanh toán tiền'),
    )
    
    user = models.ForeignKey(MyUser,on_delete=models.CASCADE)
    order = models.ForeignKey(Order,on_delete=models.CASCADE)
    amount = models.DecimalField(default=0,max_digits=8, decimal_places=0)
    status = models.CharField(max_length=30,choices=STATUS_CHOICE,default='A')
    time_order = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return self.user.username
    
    def get_value_status(self):
        return self.status
    
    def save(self, *args, **kwargs):
       if self.get_value_status() == 'D':
            pay_ = Payment.objects.filter(orderId=self.order.pk)
            if pay_.exists():
               return
            else:
                payment = Payment.objects.get_or_create(
                    paymentId = self.order.payment_method,
                    orderId = self.order.pk,
                    user = self.user,
                    order= self.order,
                    amount = self.amount,
                    payment_text_method = 'Thanh toán khi nhận hàng'
                ) 
                order_item = self.order.items.all()
                if order_item.exists():
                    for obj in order_item:
                        std_qs = Student.objects.filter(user=self.user)
                        if std_qs.exists():
                            pass
                                
                        else:
                            #add student if user is not exist in models Student
                            create_std = Student.objects.create(user=self.user)
                            #add id student auto
                            create_std.id_student = create_auto_id_std(create_std.user.id)
                            create_std.save()
                        
                        std_course_qs = StudentCourse.objects.filter(user=self.user,course=obj.item.id)
                        #da ton tai khoa hoc nay
                        if std_course_qs.exists():
                            #udpate and addition days , finish date
                            std_course = std_course_qs[0]
                            day_vip = obj.vip_days
                            finish_date = std_course.finish_date + timedelta(days=day_vip)
                            
                            if std_course.lifetime == True:
                                pass
                            else:
                                std_course.finish_date = finish_date
                                std_course.lifetime = False
                                std_course.save()
                        else:
                            #create new student course
                            start_date = datetime.now()
                            day_vip = obj.vip_days
                            finish_date = start_date + timedelta(days=day_vip)
                            create_std_cs = StudentCourse.objects.create(
                                user=self.user,
                                course=obj.item,
                                start_date=start_date,
                                finish_date=finish_date,
                                lifetime=obj.is_lifetime
                            )
       super(OrderCashOnDelivery, self).save(*args, **kwargs)
class Payment(models.Model):   
    paymentId = models.CharField(max_length=255,blank=True,null=True)
    orderId = models.CharField(max_length=255,blank=True,null=True)
    user = models.ForeignKey(MyUser,on_delete=models.CASCADE)
    order = models.ForeignKey(Order,on_delete=models.CASCADE)
    amount = models.DecimalField(default=0,max_digits=8, decimal_places=0)
    payment_text_method = models.CharField(max_length=50,blank=True,null=True)
    timestamp = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return self.user.username

order/views.py
from django.shortcuts import render,redirect,get_object_or_404
from django.contrib.auth.decorators import login_required
from course.models import Course
from .models import Order,OrderItem
from course.models import *
from django.utils import timezone 
# Create your views here.

@login_required(login_url='/login/')
def add_to_cart(request,course_id,id_vip):
    item = get_object_or_404(Course, id=course_id)
    
    option_buy_month = int(id_vip)
    vipday = 30
    is__lifetime = False
    total_price = 0
    if option_buy_month == 1:
        vipday = 30
    elif option_buy_month == 2:
        vipday = 90
    elif option_buy_month == 3:
        vipday = 365
    elif option_buy_month == 4:
        is__lifetime = True
        vipday = 18000
    else:
        return redirect('home:index')
    order_item= OrderItem.objects.get_or_create(
        item=item,
        user=request.user,
        purchased=False
        )
    order_qs = Order.objects.filter(user=request.user,ordered=False)

    if order_qs.exists():
        print("da ton tai va chua thanh toan")
        order = order_qs[0]
        if order.items.filter(item__id=item.id).exists():
            order_item[0].vip_days = vipday
            order_item[0].save()
            if option_buy_month == 1:
                total_price =  order_item[0].get_amount_saved_month()
            elif option_buy_month == 2:
                total_price =  order_item[0].get_amount_saved_quarter()
            elif option_buy_month == 3:
                total_price =  order_item[0].get_amount_saved_year()
            elif option_buy_month == 4:
                total_price =  order_item[0].get_amount_saved_lifetime()
            
            order_item[0].total_price = total_price
            order_item[0].is_lifetime = is__lifetime
            order_item[0].save()
            return redirect('payment:checkout')
            #check if the order item is in the order 
        else:
            order_item[0].vip_days = vipday
            order_item[0].save()
            if option_buy_month == 1:
                total_price =  order_item[0].get_amount_saved_month()
            elif option_buy_month == 2:
                total_price =  order_item[0].get_amount_saved_quarter()
            elif option_buy_month == 3:
                total_price =  order_item[0].get_amount_saved_year()
            elif option_buy_month == 4:
                total_price =  order_item[0].get_amount_saved_lifetime()
                
            order_item[0].total_price = total_price
            order_item[0].is_lifetime = is__lifetime
            order_item[0].save()
            order.items.add(order_item[0])
            
            return redirect('payment:checkout')
    else:
        print("tao moi gio hag")
        ordered_date = timezone.now()
        order = Order.objects.create(user=request.user,ordered_date=ordered_date)
        order_item[0].vip_days = vipday
        order_item[0].save()
        if option_buy_month == 1:
            total_price =  order_item[0].get_amount_saved_month()
        elif option_buy_month == 2:
            total_price =  order_item[0].get_amount_saved_quarter()
        elif option_buy_month == 3:
            total_price =  order_item[0].get_amount_saved_year()
        elif option_buy_month == 4:
            total_price =  order_item[0].get_amount_saved_lifetime()
        
        order_item[0].total_price = total_price
        order_item[0].is_lifetime = is__lifetime
        order_item[0].save()
        order.items.add(order_item[0])
        return redirect('payment:checkout')
 
@login_required(login_url='/login/')
def remove_item_from_cart(request,course_id):    
    item = get_object_or_404(Course, id=course_id)
    orders = Order.objects.filter(user=request.user, ordered=False)
    if orders.exists():
        order = orders[0]
        if order.items.filter(item=item).exists():
            order_item = OrderItem.objects.filter(item=item, user=request.user, purchased=False)[0]
            order.items.remove(order_item)
            order_item.delete()
            return redirect('order:cart')
        else:
            return redirect('order:cart')
    else:
        return redirect('order:cart')
    
@login_required(login_url='/login/')
def cart_view(request):
    order_item  = OrderItem.objects.filter(user=request.user,purchased=False)
    order  = Order.objects.filter(user=request.user,ordered=False)
   
    if order_item.exists() and order.exists():
        order = order[0]
        context = {
            'carts':order_item,
            'order':order,
           
        }     
        return render(request,'order/cart.html',context)
    return render(request,'order/cart.html')

def register_course(request,course_id):
    course = get_object_or_404(Course, id=course_id)
    context ={
        'course':course
    }
    return render(request,'order/register_course.html',context)

templates/order/cart.html
{% extends "pages/base.html" %} 
{% block title %} Giỏ hàng của bạn {% endblock %}
{% load humanize %}
{% load course_tag %}
{%load static%}
{%block content%} 
<section class="slider-area slider-area2">
    <div class="slider-active">
        <!-- Single Slider -->
        <div class="single-slider slider-height2">
            <div class="container">
                <div class="row">
                    <div class="col-xl-8 col-lg-11 col-md-12">
                        <div class="hero__caption hero__caption2">
                            <h1 data-animation="bounceIn" data-delay="0.2s">Giỏ hàng của bạn</h1>
                            <!-- breadcrumb Start-->
                            <nav aria-label="breadcrumb">
                                <ol class="breadcrumb">
                                    <li class="breadcrumb-item"><a href="{%url 'home:index'%}">Home</a></li>
                                    <li class="breadcrumb-item"><a href="{{request.get_full_path}}">Giỏ hàng</a></li> 
                                </ol>
                            </nav>
                            <!-- breadcrumb End -->
                        </div>
                    </div>
                </div>
            </div>          
        </div>
    </div>
</section>
<div class="container container-h-100 pb-padding mt-30">
    <!--Section: Block Content-->
    <section>

    <!--Grid row-->
    <div class="row">

        <!--Grid column-->
        <div class="col-lg-8">

        <!-- Card -->
        <div class="mb-3">
            <div class="pt-4 wish-list">
            {%if request.user.is_authenticated %}
            <h3 class="mb-4">Cart (<span> {{request.user|cart_count}}</span> items)</h3>
            {% if carts%}
            
            {%for cart in carts%}
            <div class="row mb-4">
                <div class="col-md-5 col-lg-3 col-xl-3">
                <div class="view zoom overlay z-depth-1 rounded mb-3 mb-md-0">
                    <a href="{% url 'course:detailcourse' cart.item.id %}">
                    <img class="img-fluid w-100"
                    src="{{cart.item.course_img.url}}" alt="Sample">
                    </a>
                </div>
                </div>
                <div class="col-md-7 col-lg-9 col-xl-9">
                <div>
                    <div class="d-flex justify-content-between">
                        <div>
                            <h2>{{cart.item.title}}</h2>

                            {% if cart.item.discounted_price == 0%}
                            {%else%}
                            <p class="mb-2 text-muted text-uppercase small">SALE: {{cart.item.discounted_price}} %</p>
                            {%endif%}
                            
                        </div>
                       
                     </div>
                
                    <div class="d-flex justify-content-between align-items-center">
                    <div>
                        <a href="{% url 'order:remove-item-from-cart' course_id=cart.item.id  %}" type="button" class="card-link-secondary small text-uppercase mr-3 text-dark"><i
                            class="fas fa-trash-alt mr-1"></i> Remove item </a>
                    </div>
                    {% comment %} <span class="mb-0 discount-price-cs"><span><strong >{{cart.total_price|intcomma}} <sup>đ</sup></strong></span></span> {% endcomment %}
                    <p class="mb-0"><span><strong >{{cart.total_price|intcomma}} <sup>đ</sup></strong></span></p>
                    </div>
                </div>
                </div>
            </div>
            <hr class="mb-4">
            {%endfor%}
            {%else%}
            <h2>Giỏ hàng đang trống</h2>
            {%endif%}
            <p class="text-primary mb-0"><i class="fas fa-info-circle mr-1"></i> Đừng trì hoãn việc mua hàng, thêm các mặt hàng vào giỏ hàng của bạn không có nghĩa là đặt trước chúng.</p>

            </div>
            {%else%}
            <h2>Giỏ hàng đang trống</h2>
            {%endif%}
        </div>
        <!-- Card -->

        <!-- Card -->
        <div class="mb-3">
            <div class="pt-4">

            <h5 class="mb-4">Dự kiến hàng vận chuyển</h5>

            <p class="mb-0"> Vẫn chuyển từ 3 - 5 ngày (Từ ngày đặt hàng)</p>
            </div>
        </div>
        <!-- Card -->

        <!-- Card -->
        <div class="mb-3">
            <div class="pt-4">

            <h5 class="mb-4">Thanh toán online bằng</h5>

            <img class="mr-2" width="45px"
                src="https://mdbootstrap.com/wp-content/plugins/woocommerce/includes/gateways/paypal/assets/images/paypal.png"
                alt="PayPal acceptance mark">
            </div>
        </div>
        <!-- Card -->

        </div>
        <!--Grid column-->

        <!--Grid column-->
        <div class="col-lg-4">

        <!-- Card -->
        <div class="mb-3">
            <div class="pt-4">

            <h3 class="mb-3">Thành tiền đơn hàng</h3>

            <ul class="list-group list-group-flush">
                {%if request.user.is_authenticated %}
            
            
                {%for cart in carts%}
                    <li class="list-group-item d-flex justify-content-between align-items-center border-0 px-0 pb-0">
                    {{cart.item.title}}
                    <span>{{cart.total_price|intcomma}} <sup>đ</sup></span>
                    </li>
                {%endfor%}
                {%endif%}
                <li class="list-group-item d-flex justify-content-between align-items-center px-0">
                Shipping
                <span>Free ship</span>
                </li>
                <li class="list-group-item d-flex justify-content-between align-items-center border-0 px-0 mb-3">
                <div>
                    <strong>Tổng tiền</strong>
                    <strong>
                    <p class="mb-0">(bao gồm VAT)</p>
                    </strong>
                </div>
                {%if request.user.is_authenticated %}
                    {%if order %}
                        <span><strong>{{order.get_totals|intcomma}} <sup>đ</sup></strong></span>
                    {%endif%}
                 {%endif%}
                </li>
            </ul>
            {% if carts%}
            <a type="button" href="{% url 'payment:checkout' %}" class="btn btn-primary btn-block">Thanh toán đơn hàng</a>
             {%else%}
            <a type="button" href="#" class="btn btn-primary btn-block">Thanh toán đơn hàng</a>
             {%endif%}
            </div>
        </div>
        <!-- Card -->

        

        </div>
        <!--Grid column-->

    </div>
    <!-- Grid row -->

    </section>
    <!--Section: Block Content-->
</div>
{%endblock%}

templates/order/register_course.html
{% extends "pages/base.html" %} 
{% block title %} Đăng ký khóa học {% endblock %}
{% load humanize %}
{% load course_tag %}
{%load static %} 
{%block content%}
<!--? slider Area Start-->
<section class="slider-area slider-area2">
  <div class="slider-active">
    <!-- Single Slider -->
    <div class="single-slider slider-height2">
      <div class="container">
        <div class="row">
          <div class="col-xl-8 col-lg-11 col-md-12">
            <div class="hero__caption hero__caption2">
              <h1 data-animation="bounceIn" data-delay="0.2s">Đăng ký khóa học</h1>
              <!-- breadcrumb Start-->
              <nav aria-label="breadcrumb">
                <ol class="breadcrumb">
                  <li class="breadcrumb-item">
                    <a href="{%url 'home:index'%}">Home</a>
                  </li>
                  <li class="breadcrumb-item">
                    <a href="{{request.get_full_path}}">Đăng ký: {{course.title}}</a>
                  </li>
                </ol>
              </nav>
              <!-- breadcrumb End -->
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
<div class="container container-h-100 pb-padding mt-30">
  <div class="wrapper-register-course">
      <div class="header-reg-course">
        <h2>Đăng ký mua khóa học: {{course.title}}</h2>
        <h3>Gói thành viên bắt đầu từ ₫{{course.price_month|intcomma}} / month</h3>
      </div>
      <!--Body-->
      <div class="body_reg_course">
          <div class="sub_body_reg_course">
              <div class="item-choose-price-reg mr-12">
                 
                    <div class="content1_reg_course">
                       
                        <div class="type_buy_course mr__1a">Gói tháng</div>
                        <div class="day_sum__">30 ngày</div>
                        {% discounted_price_course course.price_month course.discounted_price as discount_month%} 
                        <a href="{% url 'order:add-to-cart' course_id=course.id id_vip=1 %}" class="link_buy_course">
                          <span>₫{{discount_month|intcomma}} / month</span>
                        </a>
                      {%if course.discounted_price != 0%}

                        <p>Đang sale: {{course.discounted_price}} %</p>
                        <span class="same_price_del">Giá gốc: <del>₫{{course.price_month|intcomma}}</del></span>
                      {%endif%}
                    </div>
                 
              </div>
              <div class="item-choose-price-reg mr-12">
                  <div class="content1_reg_course">
                      
                      <div class="type_buy_course mr__1a">Gói quý</div>
                      <div class="day_sum__">90 ngày</div>
                      {% discounted_price_course course.price_quarter course.discounted_price as discount_quarter%} 
                        <a href="{% url 'order:add-to-cart' course_id=course.id id_vip=2 %}" class="link_buy_course">
                          <span>₫{{discount_quarter|intcomma}} / quarter</span>
                        </a>
                      {%if course.discounted_price != 0%}

                        <p>Đang sale: {{course.discounted_price}} %</p>
                        <span class="same_price_del">Giá gốc: <del>₫{{course.price_quarter|intcomma}}</del></span>
                      {%endif%}
                   </div>
              </div>
              <div class="item-choose-price-reg mr-12">
               
                  <div class="content1_reg_course">
                     
                      <div class="type_buy_course mr__1a">Gói năm</div>
                      <div class="day_sum__">365 ngày</div>
                      {% discounted_price_course course.price_year course.discounted_price as discount_year%} 
                        <a href="{% url 'order:add-to-cart' course_id=course.id id_vip=3 %}" class="link_buy_course">
                          <span>₫{{discount_year|intcomma}} / year</span>
                        </a>
                      {%if course.discounted_price != 0%}

                        <p>Đang sale: {{course.discounted_price}} %</p>
                        <span class="same_price_del">Giá gốc: <del>₫{{course.price_year|intcomma}}</del></span>
                      {%endif%}
                   </div>
                  
              </div>
              <div class="item-choose-price-reg mr-12">
               <div class="active_reg_course">
                  <div class="content1_reg_course">
                      <div class="kk_title">Khuyến khích</div>
                      <div class="type_buy_course">Gói trọn đời</div>
                      <div class="day_sum__">Vĩnh viễn</div>
                      {% discounted_price_course course.price_lifetime course.discounted_price as discount_lifetime%} 
                        <a href="{% url 'order:add-to-cart' course_id=course.id id_vip=4 %}" class="link_buy_course link_buy_active__">
                          <span>₫{{discount_lifetime|intcomma}} / lifetime</span>
                        </a>
                      {%if course.discounted_price != 0%}

                        <p>Đang sale: {{course.discounted_price}} %</p>
                        <span class="same_price_del">Giá gốc: <del>₫{{course.price_lifetime|intcomma}}</del></span>
                      {%endif%}
                   </div>
                  </div>
              </div>
          </div>
      </div>
  </div>
</div>

{%endblock%}